adding files
UKHomeOfficeForms/hof-component-date pull request #2
Opened 2017-02-13 16:59 UTC by joefitter

2017-02-13 17:03 UTC, lennym commented on lib/date.js
> +    throw new Error('Key must be parsed to date component');
*passed

2017-02-13 17:10 UTC, lennym requested changes

2017-02-13 17:10 UTC, lennym commented on lib/date.js
> +const validator = require('hof-form-controller/lib/validation');
I can't see where this is used, and given it's pulling in all of `hof-form-controller` it would be good to not have it.

2017-02-13 17:10 UTC, lennym commented on lib/date.js
> +const ErrorController = require('hof-controllers').error;
Also not being used. Nuke it.

2017-02-13 17:10 UTC, lennym commented on package.json
> +    "hof-form-wizard": "^1.1.0",
I don't think any of the `hof-*` dependencies are needed, and given how this should fit into a dependency tree, probably *shouldn't* be needed.

2017-02-13 17:10 UTC, lennym commented on package.json
> +    "hof-form-wizard": "^1.1.0",
I can't see where `async` is used either.

2017-02-13 17:10 UTC, lennym commented on test/lib/date.js
> +describe('Date Component', () => {});
Cool tests bro.

2017-02-13 17:12 UTC, lennym commented on lib/date.js
> +      'post-getErrors': setErrors,
I think I'd prefer it if these names matched - `get`/`set`

2017-02-13 17:38 UTC, joefitter commented on test/lib/date.js
> +describe('Date Component', () => {});
`help-wanted`

2017-02-13 17:38 UTC, joefitter commented on package.json
> +    "hof-form-wizard": "^1.1.0",
yep yep true that, left over from my messing around

2017-02-13 17:38 UTC, joefitter commented on lib/date.js
> +const ErrorController = require('hof-controllers').error;
🔥

2017-02-13 17:39 UTC, joefitter commented on lib/date.js
> +const validator = require('hof-form-controller/lib/validation');
true that, something left over from my first attempt

2017-02-13 17:39 UTC, joefitter commented on lib/date.js
> +    throw new Error('Key must be parsed to date component');
eek

2017-02-13 17:40 UTC, joefitter commented on lib/date.js
> +      'post-getErrors': setErrors,
`preGetErrors` and `postGetErrors`?

2017-02-14 13:31 UTC, joefitter commented
@lennym TESTYTESTS

2017-02-14 15:17 UTC, lennym commented
![](https://media.giphy.com/media/e9N2U72yYsTHq/giphy.gif)

2017-02-14 15:17 UTC, lennym approved these changes

2017-02-14 15:19 UTC, lennym commented
You're welcome to tell me "no", but I feel the `./lib/date.js` file might benefit from a few high-level comments explaining what each function is "doing". Even a single line on each function something like `// concat the three fields into a YYYY-MM-DD format date` etc would be really good.

2017-02-14 16:32 UTC, joefitter commented
![](https://s-media-cache-ak0.pinimg.com/736x/dc/c8/7e/dcc87edc6069c2e950766415c3748c26.jpg)

2017-02-14 16:33 UTC, joefitter commented
Yeah, I sometimes do this, I sometimes don't. On this occasion, sure why not

2017-02-14 16:33 UTC, lennym commented
I think your gif is broken.

2017-02-14 16:35 UTC, lennym commented
I'm not normally fussy about it - in most cases it's obvious enough - but here I think there's enough disconnect between the lifecycle and *what's actually happening* that I think it's worthwhile.

2017-02-14 16:36 UTC, joefitter commented
I changed it for a better one

2017-02-14 17:18 UTC, joefitter commented
@lennym howzat?

2017-02-15 11:01 UTC, lennym commented
![](https://media.giphy.com/media/l2Sq9M27jBEhUzbBm/giphy.gif)

2017-02-15 11:02 UTC, lennym commented
I'd maybe look into integration tests in future, but it looks pretty good for now.

2017-02-15 11:02 UTC, merged